// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-LHBTI8H
// DateTime: 16.12.2018 13:16:08
// UserName: Anastasia
// Input file <SimpleYacc.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using System.IO;
using ProgramTree;

namespace SimpleParser
{
public enum Tokens {
    error=1,EOF=2,BEGIN=3,END=4,CYCLE=5,ASSIGN=6,
    ASSIGNPLUS=7,ASSIGNMINUS=8,ASSIGNMULT=9,SEMICOLON=10,WRITE=11,VAR=12,
    PLUS=13,MINUS=14,MULT=15,DIV=16,MOD=17,LPAREN=18,
    RPAREN=19,COLUMN=20,IF=21,THEN=22,ELSE=23,WHILE=24,
    DO=25,REPEAT=26,UNTIL=27,COLON=28,GOTO=29,INUM=30,
    RNUM=31,ID=32};

public struct ValueType
{ 
			public double dVal; 
			public int iVal; 
			public string sVal; 
			public Node nVal;
			public ExprNode eVal;
			public StatementNode stVal;
			public BlockNode blVal;
       }
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SimpleYacc.y
// Ёти объ€влени€ добавл€ютс€ в класс GPPGParser, представл€ющий собой парсер, генерируемый системой gppg
    public BlockNode root; //  орневой узел синтаксического дерева 
    public Parser(AbstractScanner<ValueType, LexLocation> scanner) : base(scanner) { }
	private bool InDefSect = false;
  // End verbatim content from SimpleYacc.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[42];
  private static State[] states = new State[73];
  private static string[] nonTerms = new string[] {
      "progr", "expr", "ident", "T", "F", "statement", "assign", "block", "cycle", 
      "write", "empty", "var", "varlist", "if", "while", "repeat", "label", "goto", 
      "stlist", "$accept", "Anon@1", };

  static Parser() {
    states[0] = new State(new int[]{3,4},new int[]{-1,1,-8,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{32,13,29,15,3,4,5,20,11,41,12,46,21,54,24,61,26,66,4,-16,10,-16},new int[]{-19,5,-6,70,-17,9,-3,10,-18,14,-7,17,-8,18,-9,19,-10,40,-12,45,-11,52,-14,53,-15,60,-16,65});
    states[5] = new State(new int[]{4,6,10,7});
    states[6] = new State(-31);
    states[7] = new State(new int[]{32,13,29,15,3,4,5,20,11,41,12,46,21,54,24,61,26,66,4,-16,10,-16,27,-16},new int[]{-6,8,-17,9,-3,10,-18,14,-7,17,-8,18,-9,19,-10,40,-12,45,-11,52,-14,53,-15,60,-16,65});
    states[8] = new State(-4);
    states[9] = new State(-5);
    states[10] = new State(new int[]{28,11,6,71});
    states[11] = new State(new int[]{32,13,29,15,3,4,5,20,11,41,12,46,21,54,24,61,26,66,4,-16,10,-16,27,-16,23,-16},new int[]{-6,12,-17,9,-3,10,-18,14,-7,17,-8,18,-9,19,-10,40,-12,45,-11,52,-14,53,-15,60,-16,65});
    states[12] = new State(-18);
    states[13] = new State(-17);
    states[14] = new State(-6);
    states[15] = new State(new int[]{32,13},new int[]{-3,16});
    states[16] = new State(-19);
    states[17] = new State(-7);
    states[18] = new State(-8);
    states[19] = new State(-9);
    states[20] = new State(new int[]{32,13,30,28,18,29},new int[]{-2,21,-4,39,-5,38,-3,27});
    states[21] = new State(new int[]{13,23,14,32,32,13,29,15,3,4,5,20,11,41,12,46,21,54,24,61,26,66,4,-16,10,-16,27,-16,23,-16},new int[]{-6,22,-17,9,-3,10,-18,14,-7,17,-8,18,-9,19,-10,40,-12,45,-11,52,-14,53,-15,60,-16,65});
    states[22] = new State(-32);
    states[23] = new State(new int[]{32,13,30,28,18,29},new int[]{-4,24,-5,38,-3,27});
    states[24] = new State(new int[]{15,25,16,34,17,36,13,-21,14,-21,32,-21,29,-21,3,-21,5,-21,11,-21,12,-21,21,-21,24,-21,26,-21,4,-21,10,-21,27,-21,23,-21,19,-21,22,-21,25,-21});
    states[25] = new State(new int[]{32,13,30,28,18,29},new int[]{-5,26,-3,27});
    states[26] = new State(-24);
    states[27] = new State(-28);
    states[28] = new State(-29);
    states[29] = new State(new int[]{32,13,30,28,18,29},new int[]{-2,30,-4,39,-5,38,-3,27});
    states[30] = new State(new int[]{19,31,13,23,14,32});
    states[31] = new State(-30);
    states[32] = new State(new int[]{32,13,30,28,18,29},new int[]{-4,33,-5,38,-3,27});
    states[33] = new State(new int[]{15,25,16,34,17,36,13,-22,14,-22,32,-22,29,-22,3,-22,5,-22,11,-22,12,-22,21,-22,24,-22,26,-22,4,-22,10,-22,27,-22,23,-22,19,-22,22,-22,25,-22});
    states[34] = new State(new int[]{32,13,30,28,18,29},new int[]{-5,35,-3,27});
    states[35] = new State(-25);
    states[36] = new State(new int[]{32,13,30,28,18,29},new int[]{-5,37,-3,27});
    states[37] = new State(-26);
    states[38] = new State(-27);
    states[39] = new State(new int[]{15,25,16,34,17,36,13,-23,14,-23,32,-23,29,-23,3,-23,5,-23,11,-23,12,-23,21,-23,24,-23,26,-23,4,-23,10,-23,27,-23,23,-23,19,-23,22,-23,25,-23});
    states[40] = new State(-10);
    states[41] = new State(new int[]{18,42});
    states[42] = new State(new int[]{32,13,30,28,18,29},new int[]{-2,43,-4,39,-5,38,-3,27});
    states[43] = new State(new int[]{19,44,13,23,14,32});
    states[44] = new State(-33);
    states[45] = new State(-11);
    states[46] = new State(-34,new int[]{-21,47});
    states[47] = new State(new int[]{32,13},new int[]{-13,48,-3,51});
    states[48] = new State(new int[]{20,49,4,-35,10,-35,27,-35,23,-35});
    states[49] = new State(new int[]{32,13},new int[]{-3,50});
    states[50] = new State(-37);
    states[51] = new State(-36);
    states[52] = new State(-12);
    states[53] = new State(-13);
    states[54] = new State(new int[]{32,13,30,28,18,29},new int[]{-2,55,-4,39,-5,38,-3,27});
    states[55] = new State(new int[]{22,56,13,23,14,32});
    states[56] = new State(new int[]{32,13,29,15,3,4,5,20,11,41,12,46,21,54,24,61,26,66,4,-16,10,-16,27,-16,23,-16},new int[]{-6,57,-17,9,-3,10,-18,14,-7,17,-8,18,-9,19,-10,40,-12,45,-11,52,-14,53,-15,60,-16,65});
    states[57] = new State(new int[]{23,58,4,-38,10,-38,27,-38});
    states[58] = new State(new int[]{32,13,29,15,3,4,5,20,11,41,12,46,21,54,24,61,26,66,4,-16,10,-16,27,-16,23,-16},new int[]{-6,59,-17,9,-3,10,-18,14,-7,17,-8,18,-9,19,-10,40,-12,45,-11,52,-14,53,-15,60,-16,65});
    states[59] = new State(-39);
    states[60] = new State(-14);
    states[61] = new State(new int[]{32,13,30,28,18,29},new int[]{-2,62,-4,39,-5,38,-3,27});
    states[62] = new State(new int[]{25,63,13,23,14,32});
    states[63] = new State(new int[]{32,13,29,15,3,4,5,20,11,41,12,46,21,54,24,61,26,66,4,-16,10,-16,27,-16,23,-16},new int[]{-6,64,-17,9,-3,10,-18,14,-7,17,-8,18,-9,19,-10,40,-12,45,-11,52,-14,53,-15,60,-16,65});
    states[64] = new State(-40);
    states[65] = new State(-15);
    states[66] = new State(new int[]{32,13,29,15,3,4,5,20,11,41,12,46,21,54,24,61,26,66,27,-16,10,-16},new int[]{-19,67,-6,70,-17,9,-3,10,-18,14,-7,17,-8,18,-9,19,-10,40,-12,45,-11,52,-14,53,-15,60,-16,65});
    states[67] = new State(new int[]{27,68,10,7});
    states[68] = new State(new int[]{32,13,30,28,18,29},new int[]{-2,69,-4,39,-5,38,-3,27});
    states[69] = new State(new int[]{13,23,14,32,4,-41,10,-41,27,-41,23,-41});
    states[70] = new State(-3);
    states[71] = new State(new int[]{32,13,30,28,18,29},new int[]{-2,72,-4,39,-5,38,-3,27});
    states[72] = new State(new int[]{13,23,14,32,4,-20,10,-20,27,-20,23,-20});

    rules[1] = new Rule(-20, new int[]{-1,2});
    rules[2] = new Rule(-1, new int[]{-8});
    rules[3] = new Rule(-19, new int[]{-6});
    rules[4] = new Rule(-19, new int[]{-19,10,-6});
    rules[5] = new Rule(-6, new int[]{-17});
    rules[6] = new Rule(-6, new int[]{-18});
    rules[7] = new Rule(-6, new int[]{-7});
    rules[8] = new Rule(-6, new int[]{-8});
    rules[9] = new Rule(-6, new int[]{-9});
    rules[10] = new Rule(-6, new int[]{-10});
    rules[11] = new Rule(-6, new int[]{-12});
    rules[12] = new Rule(-6, new int[]{-11});
    rules[13] = new Rule(-6, new int[]{-14});
    rules[14] = new Rule(-6, new int[]{-15});
    rules[15] = new Rule(-6, new int[]{-16});
    rules[16] = new Rule(-11, new int[]{});
    rules[17] = new Rule(-3, new int[]{32});
    rules[18] = new Rule(-17, new int[]{-3,28,-6});
    rules[19] = new Rule(-18, new int[]{29,-3});
    rules[20] = new Rule(-7, new int[]{-3,6,-2});
    rules[21] = new Rule(-2, new int[]{-2,13,-4});
    rules[22] = new Rule(-2, new int[]{-2,14,-4});
    rules[23] = new Rule(-2, new int[]{-4});
    rules[24] = new Rule(-4, new int[]{-4,15,-5});
    rules[25] = new Rule(-4, new int[]{-4,16,-5});
    rules[26] = new Rule(-4, new int[]{-4,17,-5});
    rules[27] = new Rule(-4, new int[]{-5});
    rules[28] = new Rule(-5, new int[]{-3});
    rules[29] = new Rule(-5, new int[]{30});
    rules[30] = new Rule(-5, new int[]{18,-2,19});
    rules[31] = new Rule(-8, new int[]{3,-19,4});
    rules[32] = new Rule(-9, new int[]{5,-2,-6});
    rules[33] = new Rule(-10, new int[]{11,18,-2,19});
    rules[34] = new Rule(-21, new int[]{});
    rules[35] = new Rule(-12, new int[]{12,-21,-13});
    rules[36] = new Rule(-13, new int[]{-3});
    rules[37] = new Rule(-13, new int[]{-13,20,-3});
    rules[38] = new Rule(-14, new int[]{21,-2,22,-6});
    rules[39] = new Rule(-14, new int[]{21,-2,22,-6,23,-6});
    rules[40] = new Rule(-15, new int[]{24,-2,25,-6});
    rules[41] = new Rule(-16, new int[]{26,-19,27,-2});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // progr -> block
{ root = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 3: // stlist -> statement
{ 
				CurrentSemanticValue.blVal = new BlockNode(ValueStack[ValueStack.Depth-1].stVal); 
			}
        break;
      case 4: // stlist -> stlist, SEMICOLON, statement
{ 
				ValueStack[ValueStack.Depth-3].blVal.Add(ValueStack[ValueStack.Depth-1].stVal); 
				CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-3].blVal; 
			}
        break;
      case 5: // statement -> label
{CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 6: // statement -> goto
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 7: // statement -> assign
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 8: // statement -> block
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 9: // statement -> cycle
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 10: // statement -> write
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 11: // statement -> var
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 12: // statement -> empty
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 13: // statement -> if
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 14: // statement -> while
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 15: // statement -> repeat
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 16: // empty -> /* empty */
{ CurrentSemanticValue.stVal = new EmptyNode(); }
        break;
      case 17: // ident -> ID
{
			//if (!InDefSect)
				//if (!SymbolTable.vars.ContainsKey($1))
					//throw new Exception("("+@1.StartLine+","+@1.StartColumn+"): ѕеременна€ "+$1+" не описана");
			CurrentSemanticValue.eVal = new IdNode(ValueStack[ValueStack.Depth-1].sVal); 
		}
        break;
      case 18: // label -> ident, COLON, statement
{
			CurrentSemanticValue.stVal = new LabelNode(ValueStack[ValueStack.Depth-3].eVal as IdNode, ValueStack[ValueStack.Depth-1].stVal); 
		}
        break;
      case 19: // goto -> GOTO, ident
{
			CurrentSemanticValue.stVal = new GotoNode(ValueStack[ValueStack.Depth-1].eVal as IdNode); 
		}
        break;
      case 20: // assign -> ident, ASSIGN, expr
{ CurrentSemanticValue.stVal = new AssignNode(ValueStack[ValueStack.Depth-3].eVal as IdNode, ValueStack[ValueStack.Depth-1].eVal); }
        break;
      case 21: // expr -> expr, PLUS, T
{ CurrentSemanticValue.eVal = new BinOpNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'+'); }
        break;
      case 22: // expr -> expr, MINUS, T
{ CurrentSemanticValue.eVal = new BinOpNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'-'); }
        break;
      case 23: // expr -> T
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 24: // T -> T, MULT, F
{ CurrentSemanticValue.eVal = new BinOpNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'*'); }
        break;
      case 25: // T -> T, DIV, F
{ CurrentSemanticValue.eVal = new BinOpNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'/'); }
        break;
      case 26: // T -> T, MOD, F
{ CurrentSemanticValue.eVal = new BinOpNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'%'); }
        break;
      case 27: // T -> F
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 28: // F -> ident
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal as IdNode; }
        break;
      case 29: // F -> INUM
{ CurrentSemanticValue.eVal = new IntNumNode(ValueStack[ValueStack.Depth-1].iVal); }
        break;
      case 30: // F -> LPAREN, expr, RPAREN
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-2].eVal; }
        break;
      case 31: // block -> BEGIN, stlist, END
{ CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-2].blVal; }
        break;
      case 32: // cycle -> CYCLE, expr, statement
{ CurrentSemanticValue.stVal = new CycleNode(ValueStack[ValueStack.Depth-2].eVal,ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 33: // write -> WRITE, LPAREN, expr, RPAREN
{ CurrentSemanticValue.stVal = new WriteNode(ValueStack[ValueStack.Depth-2].eVal); }
        break;
      case 34: // Anon@1 -> /* empty */
{ InDefSect = true; }
        break;
      case 35: // var -> VAR, Anon@1, varlist
{ 
			foreach (var v in (ValueStack[ValueStack.Depth-1].stVal as VarDefNode).vars)
				SymbolTable.NewVarDef(v.Name, type.tint);
			InDefSect = false;	
		}
        break;
      case 36: // varlist -> ident
{ 
			CurrentSemanticValue.stVal = new VarDefNode(ValueStack[ValueStack.Depth-1].eVal as IdNode); 
		}
        break;
      case 37: // varlist -> varlist, COLUMN, ident
{ 
			(ValueStack[ValueStack.Depth-3].stVal as VarDefNode).Add(ValueStack[ValueStack.Depth-1].eVal as IdNode);
			CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-3].stVal;
		}
        break;
      case 38: // if -> IF, expr, THEN, statement
{ CurrentSemanticValue.stVal = new IfNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 39: // if -> IF, expr, THEN, statement, ELSE, statement
{ CurrentSemanticValue.stVal = new IfNode(ValueStack[ValueStack.Depth-5].eVal, ValueStack[ValueStack.Depth-3].stVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 40: // while -> WHILE, expr, DO, statement
{ CurrentSemanticValue.stVal = new WhileNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 41: // repeat -> REPEAT, stlist, UNTIL, expr
{ CurrentSemanticValue.stVal = new RepeatNode(ValueStack[ValueStack.Depth-3].blVal, ValueStack[ValueStack.Depth-1].eVal); }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
